# config.toml
baseURL = 'https://rabbitsen.github.io/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'

# mySite
theme = 'blowfish' # 主题名

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1
